version: "3"
services:
  vault:
    image: vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: 'test'
      VAULT_TOKEN: 'test'
    cap_add:
      - IPC_LOCK
    healthcheck:
      retries: 5
    command: server -dev
